### ISSUE TITLE
Bug - Liked suggested episode doesn't have a filled heart

### ISSUE THREAD

**Issue by bondif** [DevC-Casa/geeksblabla.com#129]
**Steps to reproduce:**
* Go to https://geeksblabla.com/suggest-new-episode/
* Give a like to one of the suggestions   

**Expected:** Liked suggestion has a filled heart
**Actual:** Liked suggestion has an empty heart (until page refresh)

**Comment by aboullaite** [comment]
Thanks for reporting! @yjose any thoughts ?

**Comment by yjose** [comment]
Yeah, I can confirm the bug, Nice catch @bondif,  Not sure why?  but I am going to investigate ASAP.

**Comment by Kafiil** [comment]
@yjose maybe I can take a look. Would I be able to test with auth0 locally ?

**Comment by yjose** [comment]
@Kafiil, this would be complicated to fix as you need access to AUth0 and FunaDb dashboards,
I will take care of it

**Comment by Kafiil** [comment]
You may start by looking here, `SuggestionCard.js, line 42`

`const vote = votes.data.filter(x => userVotes.includes(x._id))[0]`

Also, I think the `handelClick` function (typ there btw) should have and _id as a parameter to 
know which suggestion you need to use in the mutation

**Comment by Kafiil** [comment]
Maybe we could set up a dev environment for `auth0` and `faunaDB`

**Comment by yjose** [comment]
#135  should Fix the issue. 
The issue is related to apollo-client cache 
We are using an optimistic UI to show upvote without waiting for the response but apollo-client return data from the cache instead of the network.
using `network-only` as fetch-policy for our Queries fix the problem.  

@Kafiil , agree that we should set up some dev environment  `auth0` and `faunDB` but As I said this part for the project its a little bit complicated to do As you also need access to Netlify Account to use Netlify CLI which mean we need to create a Netlify Team ($$$). 

Anyway, I will try to find a solution but I am not sure if we can do it.
