### ISSUE TITLE
There's no contrast between Upvote card's text and and its background

### ISSUE THREAD

**Issue by melbarch** [DevC-Casa/geeksblabla.com#157]
The issue is only when using light mode (the text is visible on dark mode)
![image](https://user-images.githubusercontent.com/12951727/88438394-8b438000-ce00-11ea-988b-454fec86c044.png)

**Comment by yjose** [comment]
In case someone interested to work on fixing this issue : 

the problem is related to LoginPopup `contentStyle` background-color : https://github.com/DevC-Casa/geeksblabla.com/blob/master/src/components/Suggest/LoginPopup.js

to fix this issue we need to use a dynamic background color depends on the mode selected, here you can easily use `useTheme` to get selected mode and set the correct  background-color ( example : https://github.com/DevC-Casa/geeksblabla.com/blob/350d8da3e3ed8268516c04a1bea8a2d0cff2dd48/src/components/Home/TopEpisodes/index.js#L36)

**Comment by zakariaelas** [comment]
If it's okay with @melbarch and @yjose, I made a PR fixing this, let me know if I need to change something :pray:
