### ISSUE TITLE
GeekBlaBla Tags/Categories

### ISSUE THREAD

**Issue by ridaouiafaf** [DevC-Casa/geeksblabla.com#174]
It would be great if we can add a list in the BlaBlas nav-item contains fields that were discussed until now in the podcast.

I mean for example Frontend, Backend, Web Development, Mobile Development, MSS, AMA .. etc, so that the visitors can find what they want easily instead of scrolling down a lot of episodes to find an episode that matches their interests.

**Comment by zakariaelas** [comment]
@yjose interesting stuff .. I can start working on it this weekend if nobody has shown interest yet. Great idea @ridaouiafaf :+1:

**Comment by yjose** [comment]
Go ahead khay @zakariaelas 🏃‍♂️🏃‍♂️

**Comment by ridaouiafaf** [comment]
> @yjose interesting stuff .. I can start working on it this weekend if nobody has shown interest yet. Great idea @ridaouiafaf 👍

Go ahead good luck bro

**Comment by ridaouiafaf** [comment]
Thank you @yjose 
Thankies & Good Luck @zakariaelas

**Comment by zakariaelas** [comment]
@yjose I need help making a decision :pray:. 

You mentioned previously that we will create a new page for each tag. Just like in the mockup, the episode menu on the left will need to show the episodes that belong to a particular tag. Naturally, on each episode click, we should navigate to the episode page i.e: /blablas/building-a-resume. However, the way things are implemented currently, the episode menu will show **ALL** episodes.

What is the desired behavior in this case ?

1. Create new pages for each episode under a specific tag in order to make the episodes menu consistent with the tag choice. For example: `/tags/mss/mss-with-adnane-belmadiaf`.
2. We can rely on state and listen to user clicks on episode items. When we detect a click, we basically play it on the right hand side. In this solution, a click on an episode does not trigger a route change. Everything stays under `/tags/{tag}`.

What do you think ? Please feel free to let me know if something is not very clear. 

Thanks :pray:

**Comment by yjose** [comment]
hmm, got you, I would recommend the first option. 
Also, I would recommend removing `/tags/` from the path too and that's mean we will have multiple routes for the same episode, not bad but important for sharing. 

well, can you open a new PR with using the first option, then we can see if its the best solution

**Comment by AbdaliDahir** [comment]
guys, what about just filter posts i tested so Far it's work fine
but u Know filter its not like new "page"
and without routes here 😅

**Comment by yjose** [comment]
@AbdaliDahir Yeah you are right, but generating episodes pages is important for SEO and sharing to social media.

**Comment by zakariaelas** [comment]
@AbdaliDahir that could be an option. I'll submit a PR with the solution me and @yjose discussed yesterday, and then we can discuss the advantages and disadvantages of each solution. Would be cool if you can also take part in the discussion @AbdaliDahir as the more opinions we have the better :pray:

**Comment by AbdaliDahir** [comment]
for social share i don't think it will be a problem if we keep generating pages the filter it will work in every page for the Share "its based on slug" and u will have slug for every post under this route "/blablas/"

i'm not really good good with seo

but even with filter the meta in head is still changes
and like i mention before we have slug under "blablas/"

- disadvantages u can't share with tags category
when he will start in a page He'll stay stuck on the same page url.

for ur idea 
to generate new pages for each episode i think that u will get a lot of repetitions
u already have pages under this route "/blablas" 

- about "stays under /tags/{tag}"
in some part. it will be similar to filter 

so maybe i can say Second option "stays under /tags/{tag}" can be fine and easy to implement

Hope im little bit clear about what i say

**Comment by zakariaelas** [comment]
@AbdaliDahir I think I understood most of what you explained. Let's recap on this discussion:

### Option 1. Creating new pages for episodes under each tag + new pages for each tag:

**Overview**:
We would need to create a page for each tag i.e: `/mss/`. This would get all episodes under a specific tag and display them on the episodes menu. Once a user clicks on an episode, in order to preserve the episodes menu, we will need to encode the tag into the route. This results on having a new route like the following: `/mss/mss-with-adnane-belmadiaf/`
**Disadvantages**:
- Having two different links for each episode (repetition)

**Advantages**:
- Someone could make a point that you would not need to manage any state using this method.

### Option 2. Creating pages only for tags, use a piece of state to show the episode on the side when a user clicks on an episode:

**Overview**:
We would create pages for tags like such: `/mss`, but the following is no longer needed: `/mss/mss-with-adnane-belmadiaf`. Clicking on an episode will not navigate to a dedicated route, however, we can use state to detect when a user clicks on an episode, and display it on the right hand side (episode page). 

**Disadvantages**:

- Just as stated above, someone could mention that we would need to manage state. This implies that we will need to create new components or refactor older ones to accommodate this change. For example, the [EpisodeItem](https://github.com/DevC-Casa/geeksblabla.com/blob/master/src/components/Blabla/EpisodeItem/index.js) component is a Link, whereas in this method, it will need to behave differently even if styling and the markup is the same. If you leave the Link, when a user clicks on an episode, they will navigate to a new route, which will result in components unmounting. If your EpisodesMenu component unmounts, you will lose the state filter. 

**Advantages**:

- No repetition, The only link for displaying episodes is the following: `blablas/episode-title/`
- Relatively simpler to implement (less code). 

### Option 3. 0 new pages created, Tags should behave like a filter:

**Overview**:
We would not need to create any new pages. Clicking on a specific tag would only need to filter the list of episodes. 

**Disadvantages**:
- No pages for tags implies users will not be able to share them nor bookmark them.
- Same as option 2 disadvantages.

**Advantages**:
- Easy and simple to implement.

**Comment by zakariaelas** [comment]
On a side note, @yjose the mockup you shared only includes a few tags, however, we have quite a lot currently. Any idea on how they need to be presented ? This is what I have right now: 
![image](https://user-images.githubusercontent.com/33696020/91666561-b606af80-eaf5-11ea-9839-6a35955b2c1a.png)
One thing I don't really like about the vertical scroll is that on every route change, the scroll position is set to the start.
Should I try displaying the tags in a couple of rows instead or is this good enough ?

**Comment by yjose** [comment]
@zakariaelas  for tags I guess we can list them without vertical scroll  like  =>  https://uses.tech/
also, I would love to add numbers for tags like `uses.tech` website

**Comment by zakariaelas** [comment]
@yjose okay great, I'm on it :+1:

**Comment by yjose** [comment]
@zakariaelas thank you for the great explanation, hard to decide to be honest 😂

**Comment by yjose** [comment]
would love  if you can open the PR while you are working on it as we will have a netlify preview  to see, and maybe I can pull code and test it locally

**Comment by zakariaelas** [comment]
@yjose haha yeah definitely. Let's have at least something ready, then we can decide. I'll open a first PR asap.

**Comment by AbdaliDahir** [comment]
@zakariaelas thanks for explanation got it

the 3 is not good solution u need at least url for epsd

so im with you for solution 1/2. 🤙

if @yjose accept for "ScrollBar" can you give it more width 
im suffering with it 🤕
without mouse
