### ISSUE TITLE
Sync website notes with youtube 

### ISSUE THREAD

**Issue by yjose** [DevC-Casa/geeksblabla.com#302]
The idea is to update the youtube video description with notes and links after adding them to the website.
As the website is the source of truth would like it if you can work on a GitHub action that updates the youtube episode video with notes as a description for the video.

**Comment by azihassan** [comment]
Does this mean that the website notes should be uploaded to Youtube, or is it the other way around ?

**Comment by yjose** [comment]
@azihassan  check updated description

**Comment by azihassan** [comment]
Noice. I guess this is a three-step issue:

- Detecting new episodes. Is this based on git tags, branch name patterns, [file change detection](https://github.com/marketplace/actions/file-changes-action), or something else entirely ?
- Parsing the notes out of the markdown file. This can probably done with cat + regex if we're brave enough, but I think that a JS script with third-party libs is more maintainable in the long run.
- Updating the video. Do you have a youtube SDK in mind, or is cURL going to be enough ?

Let me know what you think.

**Comment by yjose** [comment]
Great @azihassan 
Step 1 looks great 
For the 2nd step, I would recommend using a markdown converter  (example : https://github.com/ejrbuss/markdown-to-txt/blob/master/src/markdown-to-txt.ts) 
At the end the the output text should look like the following : 
```txt

We talk about the end of study internship(PFE) in this episode. How to find a good end of studies internship? How to prepare yourself for the internship and succeed during the internship?


-------------------------------------------------
Guests

Omaima Khalil : https://twitter.com/BadQuinn3

Diaa Alhak El Fallous: https://www.linkedin.com/in/elfallous/

-------------------------------------------------
Notes

00:01:00 - Intro and welcoming.




-------------------------------------------------
Links

Building A Resume : https://geeksblabla.com/blablas/building-a-resume 


-------------------------------------------------
Prepared and Presented by

Youssouf EL Azizi : https://elazizi.com/
```
I think you can create this format using custom elements for marked render.

for youtube, I would recommend using curl if it's not possible we can use the SDK, and to be honest I don't have any idea about this 
let me know if you need more details?

**Comment by yjose** [comment]
@AbderrahimSoubaiElidrissi , @azihassan has already started working on it  but welcome if you have any inputs on this

**Comment by azihassan** [comment]
Definitely, especially since I'm not very used to Github Actions. Right now I have [an action](https://github.com/azihassan/geeksblabla.com/pull/1) that detects changes in the episode files and parses out their descriptions and Youtube URLs, but it's probably not idiomatic and needs to be refactored once it's done. For now I'll move on to the description upload part.

**Comment by azihassan** [comment]
Looks like there's no way around OAuth2 in the Youtube API. The good news is that the refresh token only expires when explicitly revoked, so we can store it as a Github secret and keep refreshing the access token as needed.

**Comment by yjose** [comment]
@azihassan i just have the chance to check the GitHub action you are working on I think is much easier to create a simple js script to convert markdown file to  description and  then call the youtube API using the same js script, I would recommend you to check how we upload  to podcast workflow: 
workflow : https://github.com/DevC-Casa/geeksblabla.com/blob/master/.github/workflows/upload_episode.yaml
script : https://github.com/DevC-Casa/geeksblabla.com/blob/master/podcast/index.js  

lets me know if you need more details

**Comment by azihassan** [comment]
Quick update.

I got the access and refresh tokens using the code in [this quickstart](https://developers.google.com/youtube/v3/quickstart/nodejs). This requires that an application be set up beforehand, with its OAuth credentials and consent screens configured. In the redirect URL, I put localhost:3000. I then listened for incoming requests using `nc -l localhost -p 3000`, copied the code I received on localhost:3000 and fed it to the aforementioned script which then exchanged it for access and refresh tokens. This was done outside of Github because it requires user interaction, so I'm not sure how (or if) we can get around this.

The client ID, client secret, access and refresh tokens are stored as env secrets on Github. The refresh token won't expire unless we revoke it. I noticed that even if I pass in an empty access token, the request still goes through. The OAuth client likely refreshes it internally. This setup seems to be working, since it managed to update the description of [a test video](https://www.youtube.com/watch?v=Wb3tIugDJFs) through a Github action, but it needs some initial setup. Also, ideally it should update the access token when it expires. Then again it's probably going to expire anyway since its lifetime is shorter than the timespan between episode uploads.

Thoughts ?

**Comment by yjose** [comment]
Thanks, @azihassan  for the update and all those information.
I can't  give you my inputs here  as I don't have enough experience with youtube API but i remember seeing this tutorial about a guy  who creates a bot to update the youtube title every few minutes, maybe can help  https://dev.to/deta/how-to-use-the-youtube-api-to-create-a-self-updating-video-title-based-on-views-59o8

But you are the expert here 😀, you can choose the right solution and provide some docs for manual tasks we need to do. it acceptable if you only need to  generate tokens manually every  few months

**Comment by azihassan** [comment]
Oh wow, can't believe I missed that resource. I ended up reverse engineering that entire process from the documentation

Alright, I'll start by writing a README.md documentation in the youtube/ directory. Not sure how it's going to be integrated in the repo once finished, but I guess we'll cross that bridge when we get to it.

**Comment by azihassan** [comment]
Added a readme file [here](https://github.com/azihassan/geeksblabla.com/blob/3dbf03bc3b5acd66eb52c293bbdf311361786245/youtube/README.md), I hope it includes everything.

**Comment by yjose** [comment]
@azihassan  can you open a new PR to start testing and review

**Comment by azihassan** [comment]
Here : https://github.com/DevC-Casa/geeksblabla.com/pull/305

I recommend squashing once we finish reviewing, there are some back and forth changes in the commits.

**Comment by yjose** [comment]
Yeah @azihassan , this is exactly what we discussed, as we are using a draft google application to access to API the token expires in 15 days and we need to generate it again. that's why we stopped running the script using GitHub action. 

we need to submit the google app to review and this requires more work
